// AUTO-GENERATED by `pnpm gen:routers`. Do not edit by hand.
// Regenerate after changing any module's /server/index.ts or modules.manifest.ts.

import { router } from "@monark/common/trpc"

import { authRouter } from "@monark/auth/server"
import { featureFlagsRouter } from "@monark/feature-flags/server"

export const appRouter = router({
  auth        : authRouter,
  featureFlags: featureFlagsRouter,
})

export type AppRouter = typeof appRouter
