import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { chromium } from "@playwright/test";
import { createServer } from "vite";

/**
 * Documentation figures. Renders the same stories the screenshot harness uses
 * (see ./capture.mjs) and writes tight, committed images into `docs/assets/`
 * for the user guide to embed.
 *
 * Separate from `capture.mjs` because the two want different output: that one
 * screenshots a whole viewport at two widths for visual review, this one
 * screenshots the component's own bounding box at one width so a figure sits
 * in a doc without a field of empty page around it.
 *
 * Usage:
 *   pnpm figures              # regenerate every figure
 *   pnpm figures records-table
 *
 * Not every harness story makes a usable figure. Several are galleries that
 * render a component in two or three labelled states side by side, which is
 * right for visual review and wrong for a user guide ; only stories that show
 * a single realistic instance are listed below.
 *
 * The figures are generated from real components with sample data, not from a
 * running app: no database, no auth, nothing to seed, and a figure can be
 * regenerated by anyone who can run the repo. The cost is that a figure shows
 * a component rather than a full screen, which is what most of the guides
 * actually need to illustrate.
 */

const FIGURES = [
  {
    name: "records-table",
    story: "fields-table",
    viewport: { width: 1360, height: 420 },
    doc: "docs/user-guide/data/the-records-table.md",
  },
  {
    name: "navigation-rail",
    story: "figure-nav-rail",
    // The rail is viewport-height and sits outside the story root's box, so
    // an element clip would cut it off : shoot the viewport instead.
    mode: "viewport",
    viewport: { width: 900, height: 420 },
    doc: "docs/user-guide/navigation/the-navigation-rail.md",
  },
  {
    name: "record-form",
    story: "fields-form",
    viewport: { width: 760, height: 900 },
    doc: "docs/user-guide/data/creating-a-record.md",
  },
  {
    name: "kanban-board",
    story: "kanban-board",
    viewport: { width: 1400, height: 560 },
    doc: "packages/kanban/docs/user-guide.md",
  },
];

const outDir = new URL("../../../../docs/assets/", import.meta.url);
const picked = process.argv.slice(2).filter((a) => !a.startsWith("--"));
const figures = picked.length ? FIGURES.filter((f) => picked.includes(f.name)) : FIGURES;

if (figures.length === 0) {
  console.error(`No figure matched. Known: ${FIGURES.map((f) => f.name).join(", ")}`);
  process.exit(1);
}

const server = await createServer({
  configFile: fileURLToPath(new URL("./vite.config.ts", import.meta.url)),
});
await server.listen();
const base = server.resolvedUrls?.local?.[0] ?? "http://localhost:5199/";

await mkdir(outDir, { recursive: true });
const browser = await chromium.launch();
const failures = [];

try {
  for (const figure of figures) {
    const page = await browser.newPage({
      viewport: figure.viewport,
      // Pin locale + timezone : a figure is committed, so it must not change
      // with the machine that generated it. Without this, date cells render
      // in the OS locale (a French date in an English guide).
      locale: "en-US",
      timezoneId: "UTC",
      // 2x so the figure stays sharp on a high-density display without being
      // rendered at a width that changes the component's own breakpoints.
      deviceScaleFactor: 2,
    });
    const errors = [];
    page.on("pageerror", (e) => errors.push(e.message));

    const query = new URLSearchParams({ story: figure.story, theme: "light" });
    await page.goto(`${base}?${query}`, { waitUntil: "load" });
    // Fonts and any editor-ish component need a beat to settle.
    await page.waitForTimeout(700);

    // Clip to the story's own box rather than the viewport, so the figure has
    // no dead space under it. `mode: "viewport"` opts out, for a component
    // positioned outside that box : a viewport-height rail or a fixed bar is
    // not inside `#root`'s rect, so an element clip would cut it off.
    const out = fileURLToPath(new URL(`${figure.name}.png`, outDir));
    if (figure.mode === "viewport") {
      await page.screenshot({ path: out });
    } else {
      await page.locator("#root").screenshot({ path: out });
    }

    if (errors.length > 0) failures.push(`${figure.name}: ${errors.join(" | ")}`);
    console.log(`✓ docs/assets/${figure.name}.png  (${figure.doc})`);
    await page.close();
  }
} finally {
  await browser.close();
  await server.close();
}

if (failures.length > 0) {
  console.error("\nPage errors:");
  for (const f of failures) console.error(`  ${f}`);
  process.exit(1);
}

console.log(`\nDone → docs/assets (${figures.length} figure(s))`);
