"use client";

import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { useTranslations } from "next-intl";
import { Check, Copy } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Skeleton } from "@/components/ui/skeleton";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { DangerCard, DangerRow } from "@/components/danger-card";
import { ConfirmDialog, FieldRow } from "@/components/patterns";
import { DirtyFormBar } from "@/components/dirty-form-bar";
import { PageHeader } from "@/components/page-header";
import { PageSection } from "@/components/page-section";
import { trpc } from "@/lib/trpc";
import { SubscriptionPicker, type SubscriptionDraft } from "./subscription-picker";
import { WebhookTabsNav } from "./webhook-tabs-nav";

// Cheap shape check before round-tripping. Server is the source of
// truth on which schemes / hosts are allowed (https always, http for
// private/loopback hosts in non-production) ; we just gate against
// "definitely not a URL" inputs here so the operator gets a snappy
// error instead of waiting for the tRPC roundtrip.
const URL_RE = /^https?:\/\/[^\s]+$/;
const EVENT_TYPE_RE = /^[a-z0-9._-]*$/;

function nextLocalId(): string {
  return `s_${Math.random().toString(36).slice(2)}`;
}

/**
 * Full-page editor for a webhook endpoint. Two modes :
 *
 *  - `create` : operator picks URL + optional description + the event
 *    types they want to receive, hits Create. The plaintext signing
 *    secret is returned exactly once and surfaced in a copy-once reveal
 *    dialog (shared with rotate) ; navigation to the new endpoint is
 *    deferred until they acknowledge it. Once they leave, it can only be
 *    regenerated by rotating.
 *  - `edit` : pre-fills from `webhooks.get`, submits via
 *    `webhooks.update`. Surfaces a "Rotate secret" + "Delete" affordance
 *    in the page footer. Disabling an endpoint via the status select
 *    pauses delivery without losing the queued outbox rows.
 */
export function WebhookEditor(
  props: (
    | {
        mode: "create";
        organizationId: string | null;
        scopeLabel: string;
      }
    | { mode: "edit"; endpointId: string }
  ) & {
    containment?: "viewport" | "container";
    onClose?: () => void;
    onCreated?: (endpointId: string) => void;
  },
) {
  const t = useTranslations("admin.webhooks.editor");
  const tManager = useTranslations("admin.webhooks.manager");
  const tCommon = useTranslations("common");
  const router = useRouter();
  const utils = trpc.useUtils();
  // Panel mode : drop the PageHeader + tab nav (the panel supplies its own
  // header ; Deliveries is reached via the full-page escape hatch), anchor
  // the save bar to the panel, and route create/delete through the panel
  // callbacks instead of a full navigation.
  const containment = props.containment ?? "viewport";
  const inPanel = containment === "container";

  // Scope field is informational-only ; it carries useful context for
  // sysadmins who can land on either platform-tier or org-scoped
  // endpoints, but for an org-admin it never holds anything other than
  // "Organization-scoped" — they can't pick anything else, so hiding
  // the field removes a useless row.
  const isSysadminQuery = trpc.rbac.isSysadmin.useQuery(undefined, {
    refetchOnWindowFocus: false,
    staleTime: Infinity,
  });
  const showScope = isSysadminQuery.data === true;

  const isEdit = props.mode === "edit";
  const endpointQuery = trpc.webhooks.get.useQuery(
    { id: isEdit ? props.endpointId : "" },
    { enabled: isEdit, refetchOnWindowFocus: false },
  );

  const [name, setName] = useState("");
  const [url, setUrl] = useState("");
  const [description, setDescription] = useState("");
  const [status, setStatus] = useState<"active" | "disabled">("active");
  const [subscriptions, setSubscriptions] = useState<SubscriptionDraft[]>([]);
  // Captured plaintext secret. Set once after a successful create or
  // rotation ; null otherwise. Survives the page session — once the
  // operator navigates away, the only way to recover the secret is
  // another rotation.
  const [revealedSecret, setRevealedSecret] = useState<string | null>(null);
  // Open state for the Rotate-secret confirm/reveal dialog. The same
  // dialog hosts both the "are you sure?" confirm and the post-rotate
  // "here's your new secret" reveal ; the body swaps based on whether
  // `revealedSecret` is set. It is also reused to reveal the create-time
  // secret (the signing secret is returned exactly once).
  const [rotateDialogOpen, setRotateDialogOpen] = useState(false);
  // Holds the just-created endpoint id while its one-time secret is shown.
  // Navigation to the created endpoint is deferred until the operator
  // acknowledges the reveal, so the secret can't be lost by an immediate
  // route change / panel remount.
  const [pendingCreatedId, setPendingCreatedId] = useState<string | null>(null);
  const [confirmDeleteOpen, setConfirmDeleteOpen] = useState(false);

  useEffect(() => {
    if (!isEdit || !endpointQuery.data) return;
    const ep = endpointQuery.data;
    setName(ep.name);
    setUrl(ep.url);
    setDescription(ep.description ?? "");
    setStatus(ep.status);
    setSubscriptions(
      ep.subscriptions.map((s) => ({
        localId: nextLocalId(),
        eventType: s.eventType,
        isPrefix: s.isPrefix,
      })),
    );
  }, [isEdit, endpointQuery.data]);

  const createMutation = trpc.webhooks.create.useMutation({
    onSuccess: async (result) => {
      toast.success(t("createSuccess"));
      await utils.webhooks.list.invalidate();
      // Reveal the one-time signing secret before leaving the create form.
      // Navigation happens on acknowledgement (see finishPendingCreate).
      setRevealedSecret(result.secret);
      setPendingCreatedId(result.endpoint.id);
      setRotateDialogOpen(true);
    },
    onError: (err) => toast.error(err.message || t("createError")),
  });

  const updateMutation = trpc.webhooks.update.useMutation({
    onSuccess: async () => {
      toast.success(t("updateSuccess"));
      if (isEdit) {
        await utils.webhooks.get.invalidate({ id: props.endpointId });
      }
      await utils.webhooks.list.invalidate();
    },
    onError: (err) => toast.error(err.message || t("updateError")),
  });

  const rotateMutation = trpc.webhooks.rotateSecret.useMutation({
    onSuccess: (result) => {
      toast.success(t("rotateSuccess"));
      setRevealedSecret(result.secret);
    },
    onError: (err) => toast.error(err.message || t("rotateError")),
  });

  const deleteMutation = trpc.webhooks.delete.useMutation({
    onSuccess: async () => {
      toast.success(t("deleteSuccess"));
      await utils.webhooks.list.invalidate();
      if (props.onClose) props.onClose();
      else router.replace("/admin/webhooks");
    },
    onError: (err) => toast.error(err.message || t("deleteError")),
  });

  function buildSubmissionSubs(): {
    eventType: string;
    isPrefix: boolean;
  }[] {
    return subscriptions
      .map((s) => ({ eventType: s.eventType.trim(), isPrefix: s.isPrefix }))
      .filter((s) => s.eventType.length > 0);
  }

  // Dirty-state vs the loaded baseline (edit) or the empty form
  // (create). Drives the sticky DirtyFormBar's visibility ; the bar
  // only slides up when the operator has actually changed something.
  const dirty = useMemo(() => {
    const subsKey = (list: ReadonlyArray<{ eventType: string; isPrefix: boolean }>): string =>
      list
        .map(
          (s: { eventType: string; isPrefix: boolean }) =>
            `${s.isPrefix ? "p" : "e"}:${s.eventType}`,
        )
        .sort()
        .join("|");
    const currentSubs = subscriptions
      .map((s) => ({ eventType: s.eventType.trim(), isPrefix: s.isPrefix }))
      .filter((s) => s.eventType.length > 0);
    if (isEdit) {
      const ep = endpointQuery.data;
      if (!ep) return false;
      if (name.trim() !== ep.name) return true;
      if (url.trim() !== ep.url) return true;
      if ((description.trim() || null) !== (ep.description ?? null)) return true;
      if (status !== ep.status) return true;
      const baselineSubs = ep.subscriptions.map((s: { eventType: string; isPrefix: boolean }) => ({
        eventType: s.eventType,
        isPrefix: s.isPrefix,
      }));
      if (subsKey(currentSubs) !== subsKey(baselineSubs)) return true;
      return false;
    }
    return (
      name.trim() !== "" || url.trim() !== "" || description.trim() !== "" || currentSubs.length > 0
    );
  }, [isEdit, endpointQuery.data, name, url, description, status, subscriptions]);

  function onCancel() {
    if (isEdit && endpointQuery.data) {
      const ep = endpointQuery.data;
      setName(ep.name);
      setUrl(ep.url);
      setDescription(ep.description ?? "");
      setStatus(ep.status);
      setSubscriptions(
        ep.subscriptions.map((s) => ({
          localId: nextLocalId(),
          eventType: s.eventType,
          isPrefix: s.isPrefix,
        })),
      );
      return;
    }
    setName("");
    setUrl("");
    setDescription("");
    setStatus("active");
    setSubscriptions([]);
  }

  function onSave() {
    handleSubmit({ preventDefault: () => {} } as React.FormEvent);
  }

  function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    const trimmedName = name.trim();
    if (trimmedName.length < 1 || trimmedName.length > 80) {
      toast.error(t("nameInvalid"));
      return;
    }
    if (!URL_RE.test(url.trim())) {
      toast.error(t("urlInvalid"));
      return;
    }
    for (const sub of subscriptions) {
      if (sub.eventType.trim() === "") continue;
      if (!EVENT_TYPE_RE.test(sub.eventType.trim())) {
        toast.error(t("eventTypeInvalid", { eventType: sub.eventType.trim() }));
        return;
      }
    }
    const trimmedDescription = description.trim();
    const subs = buildSubmissionSubs();

    if (props.mode === "create") {
      createMutation.mutate({
        organizationId: props.organizationId,
        name: trimmedName,
        url: url.trim(),
        description: trimmedDescription === "" ? null : trimmedDescription,
        subscriptions: subs,
      });
      return;
    }

    updateMutation.mutate({
      id: props.endpointId,
      name: trimmedName,
      url: url.trim(),
      description: trimmedDescription === "" ? null : trimmedDescription,
      status,
      subscriptions: subs,
    });
  }

  function openRotateDialog() {
    if (!isEdit) return;
    setRevealedSecret(null);
    setRotateDialogOpen(true);
  }

  function confirmRotate() {
    if (!isEdit) return;
    rotateMutation.mutate({ id: props.endpointId });
  }

  function closeRotateDialog() {
    setRotateDialogOpen(false);
    // Drop the revealed secret on close so it never lingers in state ;
    // the operator has either copied it or accepted the trade-off.
    setRevealedSecret(null);
    // If this reveal followed a create, complete the deferred navigation now.
    finishPendingCreate();
  }

  // Runs after the operator acknowledges a create-time secret reveal :
  // routes to the new endpoint (full page) or hands it to the panel host.
  function finishPendingCreate() {
    const id = pendingCreatedId;
    if (!id) return;
    setPendingCreatedId(null);
    if (props.onCreated) props.onCreated(id);
    else router.replace(`/admin/webhooks/${id}`);
  }

  function confirmDelete() {
    if (props.mode !== "edit") return;
    deleteMutation.mutate({ id: props.endpointId });
  }

  const [secretCopied, setSecretCopied] = useState(false);
  async function copySecret() {
    if (!revealedSecret) return;
    try {
      await navigator.clipboard.writeText(revealedSecret);
      setSecretCopied(true);
      toast.success(t("secretCopied"));
      setTimeout(() => setSecretCopied(false), 1500);
    } catch {
      toast.error(t("secretCopyError"));
    }
  }

  if (isEdit && endpointQuery.isLoading) {
    return (
      <div className="space-y-8">
        {!inPanel && (
          <PageHeader title={t("createTitle")} backHref="/admin/webhooks" backLabel={t("back")} />
        )}
        <Skeleton className="h-6 w-1/3" />
        <Skeleton className="h-32 w-full" />
        <Skeleton className="h-32 w-full" />
      </div>
    );
  }
  if (isEdit && !endpointQuery.data) {
    return (
      <div className="space-y-8">
        {!inPanel && (
          <PageHeader title={t("createTitle")} backHref="/admin/webhooks" backLabel={t("back")} />
        )}
        <p className="rounded-md border border-dashed border-border px-4 py-10 text-center text-sm text-muted-foreground">
          {t("loadError")}
        </p>
      </div>
    );
  }

  const submitting = createMutation.isPending || updateMutation.isPending;
  const orgScopeLabel =
    props.mode === "create"
      ? props.scopeLabel
      : (endpointQuery.data?.organizationId ?? null) === null
        ? tManager("orgPicker.platform")
        : t("orgScopeOrg");

  const headerTitle =
    props.mode === "create"
      ? t("createTitle")
      : endpointQuery.data?.name
        ? t("editTitle", { name: endpointQuery.data.name })
        : t("editTitleFallback");

  return (
    <div className={inPanel ? "space-y-8 pb-20" : "space-y-8"}>
      {/* Panel mode : the PanelHeader shows the create/edit title, so the
          content skips it. Full page keeps the PageHeader. */}
      {!inPanel && (
        <PageHeader
          title={headerTitle}
          subtitle={props.mode === "create" ? t("createSubtitle") : t("editSubtitle")}
          backHref="/admin/webhooks"
          backLabel={t("back")}
        />
      )}

      {isEdit && !inPanel && (
        <WebhookTabsNav endpointId={props.endpointId} activeTab="configuration" />
      )}

      <form onSubmit={handleSubmit} className="space-y-8">
        {/*
          Status sits in its own Card above the endpoint section so the
          "active vs disabled" toggle reads as the primary on/off
          decision for the endpoint — the rest of the form configures
          delivery details, but this is the kill switch. New endpoints
          default to active so the typical "create and wire up the
          receiver" flow doesn't need an extra click.
        */}
        <Card>
          <CardContent className="flex items-start justify-between gap-4 py-4">
            <div className="min-w-0 flex-1 space-y-1">
              <Label htmlFor="webhook-status" className="text-sm font-semibold">
                {t("statusLabel")}
              </Label>
              <p className="text-xs text-muted-foreground">{t("statusHint")}</p>
            </div>
            <Switch
              id="webhook-status"
              checked={status === "active"}
              onCheckedChange={(next: boolean) => setStatus(next ? "active" : "disabled")}
              aria-label={t("statusLabel")}
            />
          </CardContent>
        </Card>

        <PageSection title={t("endpointSectionTitle")}>
          <div className="@container space-y-5">
            {showScope && (
              <FieldRow label={t("scopeLabel")} htmlFor="webhook-scope">
                <Input id="webhook-scope" value={orgScopeLabel} disabled readOnly />
                <p className="text-xs text-muted-foreground">{t("scopeHint")}</p>
              </FieldRow>
            )}

            <FieldRow label={t("nameLabel")} htmlFor="webhook-name">
              <Input
                id="webhook-name"
                value={name}
                onChange={(event) => setName(event.target.value)}
                placeholder={t("namePlaceholder")}
                maxLength={80}
                required
              />
              <p className="text-xs text-muted-foreground">{t("nameHint")}</p>
            </FieldRow>

            <FieldRow label={t("urlLabel")} htmlFor="webhook-url">
              <Input
                id="webhook-url"
                type="url"
                value={url}
                onChange={(event) => setUrl(event.target.value)}
                placeholder="https://example.com/webhooks/monark"
                required
              />
              <p className="text-xs text-muted-foreground">{t("urlHint")}</p>
            </FieldRow>

            <FieldRow label={t("descriptionLabel")} htmlFor="webhook-description">
              <Textarea
                id="webhook-description"
                value={description}
                onChange={(event) => setDescription(event.target.value)}
                placeholder={t("descriptionPlaceholder")}
                rows={2}
              />
            </FieldRow>
          </div>
        </PageSection>

        <Separator />

        <PageSection title={t("subsLabel")} subtitle={t("subsSectionSubtitle")}>
          <SubscriptionPicker subscriptions={subscriptions} onChange={setSubscriptions} />
        </PageSection>
      </form>

      {isEdit && (
        <DangerCard title={t("dangerSectionTitle")}>
          <DangerRow
            title={t("rotateCta")}
            description={t("rotateRowDescription")}
            action={
              <Button
                type="button"
                variant="outline"
                onClick={openRotateDialog}
                disabled={rotateMutation.isPending}
              >
                {t("rotateCta")}
              </Button>
            }
          />
          <Separator />
          <DangerRow
            title={t("deleteCta")}
            description={t("deleteRowDescription")}
            action={
              <Button
                type="button"
                variant="destructive"
                onClick={() => setConfirmDeleteOpen(true)}
                disabled={deleteMutation.isPending}
              >
                {t("deleteCta")}
              </Button>
            }
          />
        </DangerCard>
      )}

      <Dialog
        open={rotateDialogOpen}
        onOpenChange={(next) => {
          // Block dismissal mid-rotation so the operator can't lose the
          // freshly minted secret by clicking outside the dialog before
          // the mutation settles.
          if (!next && rotateMutation.isPending) return;
          if (!next) closeRotateDialog();
          else setRotateDialogOpen(true);
        }}
      >
        <DialogContent>
          {revealedSecret ? (
            <>
              <DialogHeader>
                <DialogTitle>{t("secretRevealedTitle")}</DialogTitle>
                <DialogDescription>{t("secretRevealedSubtitle")}</DialogDescription>
              </DialogHeader>
              {/*
                Same codeblock + top-right copy-icon pattern as the
                TOTP recovery codes view. The secret is an opaque
                token so a one-line scrollable mono block reads
                better than a wrapped chunk, and the icon-button
                swap (Copy → Check on success) gives instant
                feedback without needing a toast to fire.
              */}
              <div className="relative py-2">
                <pre className="overflow-x-auto rounded-md border border-border bg-muted px-4 py-3 pr-12 font-mono text-xs leading-relaxed text-foreground">
                  {revealedSecret}
                </pre>
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  onClick={copySecret}
                  aria-label={t("secretCopy")}
                  title={t("secretCopy")}
                  className="absolute right-1.5 top-3.5 h-7 w-7 text-muted-foreground hover:text-foreground"
                >
                  {secretCopied ? (
                    <Check className="h-3.5 w-3.5" aria-hidden />
                  ) : (
                    <Copy className="h-3.5 w-3.5" aria-hidden />
                  )}
                </Button>
              </div>
              <DialogFooter>
                <Button type="button" onClick={closeRotateDialog}>
                  {t("rotateDone")}
                </Button>
              </DialogFooter>
            </>
          ) : (
            <>
              <DialogHeader>
                <DialogTitle>{t("rotateCta")}</DialogTitle>
                <DialogDescription>{t("rotateConfirm")}</DialogDescription>
              </DialogHeader>
              <DialogFooter>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setRotateDialogOpen(false)}
                  disabled={rotateMutation.isPending}
                >
                  {t("cancel")}
                </Button>
                <Button type="button" onClick={confirmRotate} disabled={rotateMutation.isPending}>
                  {rotateMutation.isPending ? t("rotateConfirming") : t("rotateCta")}
                </Button>
              </DialogFooter>
            </>
          )}
        </DialogContent>
      </Dialog>

      <ConfirmDialog
        open={confirmDeleteOpen}
        onOpenChange={setConfirmDeleteOpen}
        title={t("deleteCta")}
        description={t("deleteConfirm", { url: endpointQuery.data?.url ?? "" })}
        cancelLabel={t("cancel")}
        confirmLabel={t("deleteCta")}
        isPending={deleteMutation.isPending}
        onConfirm={confirmDelete}
      />

      <DirtyFormBar
        containment={containment}
        open={dirty}
        onSave={onSave}
        onCancel={onCancel}
        saving={submitting}
        saveLabel={props.mode === "create" ? t("create") : t("save")}
        savingLabel={t("submitting")}
        cancelLabel={t("cancel")}
        message={tCommon("unsavedChanges")}
      />
    </div>
  );
}
