import { readFile, writeFile, access } from "node:fs/promises"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { MODULES } from "../modules.manifest.js"
import { packageDirName, moduleEventsTypeName } from "./lib/names.js"

const __dirname = dirname(fileURLToPath(import.meta.url))
const APP_ROOT = resolve(__dirname, "..")
const OUTPUT_PATH = resolve(
  APP_ROOT,
  "packages/common/src/contracts/events.generated.ts",
)

const HEADER = `// AUTO-GENERATED by \`pnpm gen:events\`. Do not edit by hand.
// Regenerate after changing any module's /contracts/events.ts or modules.manifest.ts.

`

async function exists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

async function renderGeneratedFile(): Promise<string> {
  const names = Object.keys(MODULES).sort()

  if (names.length === 0) {
    return `${HEADER}import type { DomainEventBase } from "./events.js"

// No modules registered yet. Once modules exist, this union is widened
// to the sum of every registered module's <Module>Events union.
export type DomainEvent = DomainEventBase
`
  }

  const missing: string[] = []
  for (const name of names) {
    const p = resolve(APP_ROOT, "packages", packageDirName(name), "src/contracts/events.ts")
    if (!(await exists(p))) {
      missing.push(`${name} (expected ${p})`)
    }
  }
  if (missing.length > 0) {
    throw new Error(
      `gen:events: missing contracts/events.ts in modules:\n  ${missing.join("\n  ")}`,
    )
  }

  const imports = names
    .map((name) => {
      const typeName = moduleEventsTypeName(name)
      return `import type { ${typeName} } from "${name}/contracts"`
    })
    .join("\n")

  const union = names.map((name) => `  | ${moduleEventsTypeName(name)}`).join("\n")

  return `${HEADER}${imports}

export type DomainEvent =
${union}
`
}

async function main() {
  const checkMode = process.argv.includes("--check")
  const rendered = await renderGeneratedFile()

  if (checkMode) {
    const current = (await exists(OUTPUT_PATH)) ? await readFile(OUTPUT_PATH, "utf8") : ""
    if (current !== rendered) {
      console.error(
        "gen:events --check FAILED: events.generated.ts is out of date. Run `pnpm gen:events` and commit.",
      )
      process.exit(1)
    }
    console.log("gen:events --check ok")
    return
  }

  await writeFile(OUTPUT_PATH, rendered, "utf8")
  console.log(`gen:events: wrote ${OUTPUT_PATH}`)
}

main().catch((error: unknown) => {
  console.error(error)
  process.exit(1)
})
