import { readFile, writeFile, access } from "node:fs/promises"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { MODULES } from "../modules.manifest.js"
import { packageDirName, moduleRouterName, routerKey } from "./lib/names.js"

const __dirname = dirname(fileURLToPath(import.meta.url))
const APP_ROOT = resolve(__dirname, "..")
const OUTPUT_PATH = resolve(APP_ROOT, "services/api/src/trpc/app-router.generated.ts")

const HEADER = `// AUTO-GENERATED by \`pnpm gen:routers\`. Do not edit by hand.
// Regenerate after changing any module's /server/index.ts or modules.manifest.ts.

`

async function exists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

async function renderGeneratedFile(): Promise<string> {
  const names = Object.keys(MODULES).sort()

  if (names.length === 0) {
    return `${HEADER}import { router } from "@monark/common/trpc"

// No modules registered yet. Once modules exist, each exports a named
// sub-router (authRouter, votingRouter, etc.) and this file composes them.
export const appRouter = router({})
export type AppRouter = typeof appRouter
`
  }

  const missing: string[] = []
  for (const name of names) {
    const p = resolve(APP_ROOT, "packages", packageDirName(name), "src/server/index.ts")
    if (!(await exists(p))) {
      missing.push(`${name} (expected ${p})`)
    }
  }
  if (missing.length > 0) {
    throw new Error(
      `gen:routers: missing server/index.ts in modules:\n  ${missing.join("\n  ")}`,
    )
  }

  const imports = names
    .map((name) => {
      const routerVar = moduleRouterName(name)
      return `import { ${routerVar} } from "${name}/server"`
    })
    .join("\n")

  const longestKeyLength = Math.max(...names.map((n) => routerKey(n).length))
  const entries = names
    .map((name) => {
      const key = routerKey(name)
      const padded = key.padEnd(longestKeyLength)
      return `  ${padded}: ${moduleRouterName(name)},`
    })
    .join("\n")

  return `${HEADER}import { router } from "@monark/common/trpc"

${imports}

export const appRouter = router({
${entries}
})

export type AppRouter = typeof appRouter
`
}

async function main() {
  const checkMode = process.argv.includes("--check")
  const rendered = await renderGeneratedFile()

  if (checkMode) {
    const current = (await exists(OUTPUT_PATH)) ? await readFile(OUTPUT_PATH, "utf8") : ""
    if (current !== rendered) {
      console.error(
        "gen:routers --check FAILED: app-router.generated.ts is out of date. Run `pnpm gen:routers` and commit.",
      )
      process.exit(1)
    }
    console.log("gen:routers --check ok")
    return
  }

  await writeFile(OUTPUT_PATH, rendered, "utf8")
  console.log(`gen:routers: wrote ${OUTPUT_PATH}`)
}

main().catch((error: unknown) => {
  console.error(error)
  process.exit(1)
})
